[workspace]
resolver = "3"
members = [
    "datalit",
    "datalit-macros",
    "datalit-macros-internals"
]

# Licensing
license = "MIT OR Apache-2.0"
license-file = ["LICENSE-MIT", "LICENSE-APACHE"]