[package]
name = "datalit-macros"
version = "0.1.0-prerelease"
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.101"
datalit-macros-internals = { path = "../datalit-macros-internals" }
