[package]
name = "datalit-macros"
license.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
documentation.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.101"
datalit-macros-internals = { workspace = true }
